name: PetPickup
version: '1.2-SNAPSHOT'
main: me.spectral8420.petPickup.PetPickup
api-version: '1.21'
authors: [ ____Spectral____ ]
description: A fun minigame for Minecraft!

commands:
  pp:
    description: "Toggle pet pickup"
    permission: "pp.toggle"