whitelistedTypes:
  - "ARMADILLO"
  - "AXOLOTL"
  - "CAMEL"
  - "CAT"
  - "CHICKEN"
  - "FOX"
  - "FROG"
  - "HAPPY_GHAST"
  - "SQUID"
  - "GLOW_SQUID"
  - "GOAT"
  - "HORSE"
  - "IRON_GOLEM"
  - "LLAMA"
  - "MOOSHROOM"
  - "MULE"
  - "NAUTILUS"
  - "PANDA"
  - "PARROT"
  - "POLAR_BEAR"
  - "RABBIT"
  - "SKELETON_HORSE"
  - "SNIFFER"
  - "SNOW_GOLEM"
  - "STRIDER"
  - "TRADER_LLAMA"
  - "TURTLE"
  - "VILLAGER"
  - "WANDERING_TRADER"
  - "WOLF"
  - "ZOMBIE_HORSE"